name: Google Analytics
package-name: aldryn-google-analytics
url: https://github.com/aldryn/aldryn-google-analytics
author:
  name: Divio AG
  url: https://www.divio.ch
installed-apps:
  - aldryn_google_analytics
version: 0.0.6
description: Attach Google Analytics tracking script to the site
license:
  name: BSD
  text: !literal-include LICENSE.txt
